branch-defaults:
  master:
    environment: development
global:
  application_name: RPG
  default_ec2_keyname: null
  default_platform: 64bit Amazon Linux 2014.09 v1.1.0 running Node.js
  default_region: us-west-1
  profile: null
  sc: git
